export const CARD_BG = [
  { id: 1, bgcolor: 'linear-gradient(135deg, #e6f8f3 0%, #f7fcfa 100%)' },
  { id: 2, bgcolor: 'linear-gradient(135deg, #fef9e7 0%, #fffdf4 100%)' },
  { id: 3, bgcolor: 'linear-gradient(135deg, #eaf7ff 0%, #f3fbff 100%)' },
  { id: 4, bgcolor: 'linear-gradient(135deg, #fff2e9 0%, #fff8f3 100%)' },
  { id: 5, bgcolor: 'linear-gradient(135deg, #e7f6f6 0%, #f4fafd 100%)' },
  { id: 6, bgcolor: 'linear-gradient(135deg, #f5f5f2 0%, #fbfbfb 100%)' },
  { id: 7, bgcolor: 'linear-gradient(135deg, #fff4fc 0%, #fff8fd 100%)' },
  { id: 8, bgcolor: 'linear-gradient(135deg, #e8fef3 0%, #f5fef8 100%)' },
  { id: 9, bgcolor: 'linear-gradient(135deg, #f0ecff 0%, #f7f5ff 100%)' },
  { id: 10, bgcolor: 'linear-gradient(135deg, #fef2f2 0%, #fff8f8 100%)' },
];

export const APP_FEATURES = [
  {
    id: 1,
    title: 'Tailored Just for you',
    description: 'Get interview questions and answers based on your role, experince, and specific focus areas. Our AI-powered system curates personalized interview sets that match your unique profile and goals.',
  },
  {
    id: 2,
    title: 'Learn at Your Own Pace',
    description: "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered detailed explanations.",
  },
  {
    id: 3,
    title: 'Capture Your Insights',
    description: 'Add personal notes to any question and pin important ones to the top - makinng your lewarning more organized.',
  },
  {
    id: 4,
    title: 'Understand the "Why" Behind answers',
    description: 'Beyond just answers, unlock detailed concept explanations generated by AI that help you grasp the underlying concepts and principles.',
  },
   {
    id: 5,
    title: 'Save, Orgganize and Revisit',
    description: 'Easily save your interview sets, organize them neatly in your dashboard, and revisit them anytime to reinforce your learning.',
  },
];

