

export const APP_FEATURES = [
  {
    id: 1,
    title: 'Tailored Just for you',
    description: 'Get interview questions and answers based on your role, experince, and specific focus areas. Our AI-powered system curates personalized interview sets that match your unique profile and goals.',
  },
  {
    id: 2,
    title: 'Learn at Your Own Pace',
    description: "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered detailed explanations.",
  },
  {
    id: 3,
    title: 'Capture Your Insights',
    description: 'Add personal notes to any question and pin important ones to the top - makinng your lewarning more organized.',
  },
  {
    id: 4,
    title: 'Understand the "Why" Behind answers',
    description: 'Beyond just answers, unlock detailed concept explanations generated by AI that help you grasp the underlying concepts and principles.',
  },
   {
    id: 5,
    title: 'Save, Orgganize and Revisit',
    description: 'Easily save your interview sets, organize them neatly in your dashboard, and revisit them anytime to reinforce your learning.',
  },
];